### ISSUE TITLE
Can you show ROUGE-score?

### ISSUE THREAD

**Issue by odek53r** [rockingdingo/deepnlp#4]
Can you show ROUGE scores of the model trained on SogouCS corpus? thanks

**Comment by rockingdingo** [comment]
Hi @odek53r  I don't have the ROUGE score for the testing dataset yet, because the overall textsum task on this Chinese news corpus is quite low compared to the score published by papers on the Megaword corpus. But if you want to test a specific example, you can try the examples in the data/test folder, which will give you a sense on the ROUGE score of Bi-gram.
